### ISSUE TITLE
Memberlist Secret is outputted to console

### ISSUE THREAD

**Issue by colinwilson** [colinwilson/terraform-kubernetes-metallb#1]
The generated `secretkey` contained in the `memberlist` secret is exposed via the console when `terraform plan` or `terraform apply` is run.
https://github.com/colinwilson/terraform-kubernetes-metallb/blob/a055a877763afef7f454eb79320e31614100b2e4/memberlist_secret.tf#L2-L4

EDIT: Related to https://github.com/hashicorp/terraform-provider-random/issues/66

**Comment by aceat64** [comment]
This issue can be closed, the resource was changed to `random_password` which marks the data as sensitive. I ran a test locally and verified that the memberlist secret is no longer exposed.

**Comment by colinwilson** [comment]
Thank you. I'll update this.

**Comment by colinwilson** [comment]
fixed by f4049b2
